presets = dict()

presets["RoyCarver"] = {
    "building_name":"RoyCarver",
    "architecture_files": [
        "cad_files/RoyCarver/Architecture/RCARLL2.dxf",
        "cad_files/RoyCarver/Architecture/RCARLL.dxf",
        "cad_files/RoyCarver/Architecture/RCAR01.dxf",
        "cad_files/RoyCarver/Architecture/RCAR02.dxf",
        "cad_files/RoyCarver/Architecture/RCAR03.dxf",
        "cad_files/RoyCarver/Architecture/RCAR04.dxf",
        "cad_files/RoyCarver/Architecture/RCAR05.dxf",
        "cad_files/RoyCarver/Architecture/RCAR06.dxf",
        "cad_files/RoyCarver/Architecture/RCAR07.dxf",
        "cad_files/RoyCarver/Architecture/RCAR08.dxf",
        "cad_files/RoyCarver/Architecture/RCAR09.dxf",
    ],
    "label_files": [
        "cad_files/RoyCarver/Space/RCSPLL2.dxf",
        "cad_files/RoyCarver/Space/RCSPLL.dxf",
        "cad_files/RoyCarver/Space/RCSP01.dxf",
        "cad_files/RoyCarver/Space/RCSP02.dxf",
        "cad_files/RoyCarver/Space/RCSP03.dxf",
        "cad_files/RoyCarver/Space/RCSP04.dxf",
        "cad_files/RoyCarver/Space/RCSP05.dxf",
        "cad_files/RoyCarver/Space/RCSP06.dxf",
        "cad_files/RoyCarver/Space/RCSP07.dxf",
        "cad_files/RoyCarver/Space/RCSP08.dxf",
        "cad_files/RoyCarver/Space/RCSP09.dxf",
    ],
}

presets["ChildrensHospital"] = {
    "building_name":"ChildrensHospital",
    "architecture_files": [
        "cad_files/ChildrensHospital/Architecture/SFCHARLL2.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHARLL.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR01.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR02.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR03.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR04.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR05.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR06.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR07.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR08.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR09.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR10.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR11.dxf",
        "cad_files/ChildrensHospital/Architecture/SFCHAR12.dxf",
    ],
    "label_files": [
        "cad_files/ChildrensHospital/Space/SFCHSPLL.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSPLL2.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP01.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP02.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP03.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP04.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP05.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP06.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP07.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP08.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP09.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP10.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP11.dxf",
        "cad_files/ChildrensHospital/Space/SFCHSP12.dxf",
    ],
}

presets["JohnColloton"] = {
    "building_name":"JohnColloton",
    "architecture_files": [
        "cad_files/JohnColloton/Architecture/JCHARLL2.dxf",
        "cad_files/JohnColloton/Architecture/JCHARLL.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR01.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR02.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR03.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR04.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR05.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR06.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR07.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR08.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR09.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR10.dxf",
        "cad_files/JohnColloton/Architecture/JCHAR01.dxf",
    ],
    "label_files": [
        "cad_files/JohnColloton/Space/JCSPLL2.dxf",
        "cad_files/JohnColloton/Space/JCSPLL.dxf",
        "cad_files/JohnColloton/Space/JCSP01.dxf",
        "cad_files/JohnColloton/Space/JCSP02.dxf",
        "cad_files/JohnColloton/Space/JCSP03.dxf",
        "cad_files/JohnColloton/Space/JCSP04.dxf",
        "cad_files/JohnColloton/Space/JCSP05.dxf",
        "cad_files/JohnColloton/Space/JCSP06.dxf",
        "cad_files/JohnColloton/Space/JCSP07.dxf",
        "cad_files/JohnColloton/Space/JCSP08.dxf",
        "cad_files/JohnColloton/Space/JCSP09.dxf",
        "cad_files/JohnColloton/Space/JCSP10.dxf",
    ],
}


presets["JohnPappajohn"] = {
    "building_name":"JohnColloton",
    "architecture_files": [
        "cad_files/JohnPappajohn/Architecture/JPARLL3.dxf",
        "cad_files/JohnPappajohn/Architecture/JPARLL2.dxf",
        "cad_files/JohnPappajohn/Architecture/JPARLL.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR01.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR02.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR03.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR04.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR05.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR06.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR07.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR08.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR09.dxf",
        "cad_files/JohnPappajohn/Architecture/JPAR10.dxf",
    ],
    "label_files": [
        "cad_files/JohnPappajohn/Space/JPSPLL3.dxf",
        "cad_files/JohnPappajohn/Space/JPSPLL2.dxf",
        "cad_files/JohnPappajohn/Space/JPSPLL.dxf",
        "cad_files/JohnPappajohn/Space/JPSP01.dxf",
        "cad_files/JohnPappajohn/Space/JPSP02.dxf",
        "cad_files/JohnPappajohn/Space/JPSP03.dxf",
        "cad_files/JohnPappajohn/Space/JPSP04.dxf",
        "cad_files/JohnPappajohn/Space/JPSP05.dxf",
        "cad_files/JohnPappajohn/Space/JPSP06.dxf",
        "cad_files/JohnPappajohn/Space/JPSP07.dxf",
        "cad_files/JohnPappajohn/Space/JPSP08.dxf",
        "cad_files/JohnPappajohn/Space/JPSP09.dxf",
        "cad_files/JohnPappajohn/Space/JPSP10.dxf",
    ],
}


